# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ modified ]
  pull_request:
    branches: [ modified ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      name: Check out code
      
    - run: yarn install
    - run: cp /scripts/build/* .
    - run: ./client.sh
    - run: ./embed.sh
    - run: ./index.sh
    - run: ./server.sh
